project:
  type: website
  output-dir: docs

website:
  title: "Welcome to Elena’s Page"
  navbar:
    left:
      - href: index.qmd
        text: Home
#      - about.qmd
      - hobbies.qmd

format:
  html:
    theme: vapor
    mainfont: arial
    fontsize: 1.5rem
    monofont: courier new
    css: styles.css
    toc: true



